// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: backend/pkg/server/proto/state_expiry/state_expiry.proto

package state_expiry

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// StateExpiryServiceClient is the client API for StateExpiryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateExpiryServiceClient interface {
}

type stateExpiryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateExpiryServiceClient(cc grpc.ClientConnInterface) StateExpiryServiceClient {
	return &stateExpiryServiceClient{cc}
}

// StateExpiryServiceServer is the server API for StateExpiryService service.
// All implementations must embed UnimplementedStateExpiryServiceServer
// for forward compatibility
type StateExpiryServiceServer interface {
	mustEmbedUnimplementedStateExpiryServiceServer()
}

// UnimplementedStateExpiryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStateExpiryServiceServer struct {
}

func (UnimplementedStateExpiryServiceServer) mustEmbedUnimplementedStateExpiryServiceServer() {}

// UnsafeStateExpiryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateExpiryServiceServer will
// result in compilation errors.
type UnsafeStateExpiryServiceServer interface {
	mustEmbedUnimplementedStateExpiryServiceServer()
}

func RegisterStateExpiryServiceServer(s grpc.ServiceRegistrar, srv StateExpiryServiceServer) {
	s.RegisterService(&StateExpiryService_ServiceDesc, srv)
}

// StateExpiryService_ServiceDesc is the grpc.ServiceDesc for StateExpiryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateExpiryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "state_expiry.StateExpiryService",
	HandlerType: (*StateExpiryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "backend/pkg/server/proto/state_expiry/state_expiry.proto",
}
