// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: backend/pkg/api/proto/lab_api.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/ethpandaops/lab/backend/pkg/api/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LabAPIName is the fully-qualified name of the LabAPI service.
	LabAPIName = "labapi.LabAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LabAPIGetRecentLocallyBuiltBlocksProcedure is the fully-qualified name of the LabAPI's
	// GetRecentLocallyBuiltBlocks RPC.
	LabAPIGetRecentLocallyBuiltBlocksProcedure = "/labapi.LabAPI/GetRecentLocallyBuiltBlocks"
	// LabAPIGetSlotDataProcedure is the fully-qualified name of the LabAPI's GetSlotData RPC.
	LabAPIGetSlotDataProcedure = "/labapi.LabAPI/GetSlotData"
	// LabAPIGetConfigProcedure is the fully-qualified name of the LabAPI's GetConfig RPC.
	LabAPIGetConfigProcedure = "/labapi.LabAPI/GetConfig"
	// LabAPIGetStateExpiryInfoProcedure is the fully-qualified name of the LabAPI's GetStateExpiryInfo
	// RPC.
	LabAPIGetStateExpiryInfoProcedure = "/labapi.LabAPI/GetStateExpiryInfo"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	labAPIServiceDescriptor                           = proto.File_backend_pkg_api_proto_lab_api_proto.Services().ByName("LabAPI")
	labAPIGetRecentLocallyBuiltBlocksMethodDescriptor = labAPIServiceDescriptor.Methods().ByName("GetRecentLocallyBuiltBlocks")
	labAPIGetSlotDataMethodDescriptor                 = labAPIServiceDescriptor.Methods().ByName("GetSlotData")
	labAPIGetConfigMethodDescriptor                   = labAPIServiceDescriptor.Methods().ByName("GetConfig")
	labAPIGetStateExpiryInfoMethodDescriptor          = labAPIServiceDescriptor.Methods().ByName("GetStateExpiryInfo")
)

// LabAPIClient is a client for the labapi.LabAPI service.
type LabAPIClient interface {
	GetRecentLocallyBuiltBlocks(context.Context, *connect.Request[proto.GetRecentLocallyBuiltBlocksRequest]) (*connect.Response[proto.GetRecentLocallyBuiltBlocksResponse], error)
	GetSlotData(context.Context, *connect.Request[proto.GetSlotDataRequest]) (*connect.Response[proto.GetSlotDataResponse], error)
	GetConfig(context.Context, *connect.Request[proto.GetConfigRequest]) (*connect.Response[proto.GetConfigResponse], error)
	GetStateExpiryInfo(context.Context, *connect.Request[proto.GetStateExpiryInfoRequest]) (*connect.Response[proto.GetStateExpiryInfoResponse], error)
}

// NewLabAPIClient constructs a client for the labapi.LabAPI service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLabAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LabAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &labAPIClient{
		getRecentLocallyBuiltBlocks: connect.NewClient[proto.GetRecentLocallyBuiltBlocksRequest, proto.GetRecentLocallyBuiltBlocksResponse](
			httpClient,
			baseURL+LabAPIGetRecentLocallyBuiltBlocksProcedure,
			connect.WithSchema(labAPIGetRecentLocallyBuiltBlocksMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getSlotData: connect.NewClient[proto.GetSlotDataRequest, proto.GetSlotDataResponse](
			httpClient,
			baseURL+LabAPIGetSlotDataProcedure,
			connect.WithSchema(labAPIGetSlotDataMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getConfig: connect.NewClient[proto.GetConfigRequest, proto.GetConfigResponse](
			httpClient,
			baseURL+LabAPIGetConfigProcedure,
			connect.WithSchema(labAPIGetConfigMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getStateExpiryInfo: connect.NewClient[proto.GetStateExpiryInfoRequest, proto.GetStateExpiryInfoResponse](
			httpClient,
			baseURL+LabAPIGetStateExpiryInfoProcedure,
			connect.WithSchema(labAPIGetStateExpiryInfoMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// labAPIClient implements LabAPIClient.
type labAPIClient struct {
	getRecentLocallyBuiltBlocks *connect.Client[proto.GetRecentLocallyBuiltBlocksRequest, proto.GetRecentLocallyBuiltBlocksResponse]
	getSlotData                 *connect.Client[proto.GetSlotDataRequest, proto.GetSlotDataResponse]
	getConfig                   *connect.Client[proto.GetConfigRequest, proto.GetConfigResponse]
	getStateExpiryInfo          *connect.Client[proto.GetStateExpiryInfoRequest, proto.GetStateExpiryInfoResponse]
}

// GetRecentLocallyBuiltBlocks calls labapi.LabAPI.GetRecentLocallyBuiltBlocks.
func (c *labAPIClient) GetRecentLocallyBuiltBlocks(ctx context.Context, req *connect.Request[proto.GetRecentLocallyBuiltBlocksRequest]) (*connect.Response[proto.GetRecentLocallyBuiltBlocksResponse], error) {
	return c.getRecentLocallyBuiltBlocks.CallUnary(ctx, req)
}

// GetSlotData calls labapi.LabAPI.GetSlotData.
func (c *labAPIClient) GetSlotData(ctx context.Context, req *connect.Request[proto.GetSlotDataRequest]) (*connect.Response[proto.GetSlotDataResponse], error) {
	return c.getSlotData.CallUnary(ctx, req)
}

// GetConfig calls labapi.LabAPI.GetConfig.
func (c *labAPIClient) GetConfig(ctx context.Context, req *connect.Request[proto.GetConfigRequest]) (*connect.Response[proto.GetConfigResponse], error) {
	return c.getConfig.CallUnary(ctx, req)
}

// GetStateExpiryInfo calls labapi.LabAPI.GetStateExpiryInfo.
func (c *labAPIClient) GetStateExpiryInfo(ctx context.Context, req *connect.Request[proto.GetStateExpiryInfoRequest]) (*connect.Response[proto.GetStateExpiryInfoResponse], error) {
	return c.getStateExpiryInfo.CallUnary(ctx, req)
}

// LabAPIHandler is an implementation of the labapi.LabAPI service.
type LabAPIHandler interface {
	GetRecentLocallyBuiltBlocks(context.Context, *connect.Request[proto.GetRecentLocallyBuiltBlocksRequest]) (*connect.Response[proto.GetRecentLocallyBuiltBlocksResponse], error)
	GetSlotData(context.Context, *connect.Request[proto.GetSlotDataRequest]) (*connect.Response[proto.GetSlotDataResponse], error)
	GetConfig(context.Context, *connect.Request[proto.GetConfigRequest]) (*connect.Response[proto.GetConfigResponse], error)
	GetStateExpiryInfo(context.Context, *connect.Request[proto.GetStateExpiryInfoRequest]) (*connect.Response[proto.GetStateExpiryInfoResponse], error)
}

// NewLabAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLabAPIHandler(svc LabAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	labAPIGetRecentLocallyBuiltBlocksHandler := connect.NewUnaryHandler(
		LabAPIGetRecentLocallyBuiltBlocksProcedure,
		svc.GetRecentLocallyBuiltBlocks,
		connect.WithSchema(labAPIGetRecentLocallyBuiltBlocksMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	labAPIGetSlotDataHandler := connect.NewUnaryHandler(
		LabAPIGetSlotDataProcedure,
		svc.GetSlotData,
		connect.WithSchema(labAPIGetSlotDataMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	labAPIGetConfigHandler := connect.NewUnaryHandler(
		LabAPIGetConfigProcedure,
		svc.GetConfig,
		connect.WithSchema(labAPIGetConfigMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	labAPIGetStateExpiryInfoHandler := connect.NewUnaryHandler(
		LabAPIGetStateExpiryInfoProcedure,
		svc.GetStateExpiryInfo,
		connect.WithSchema(labAPIGetStateExpiryInfoMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/labapi.LabAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LabAPIGetRecentLocallyBuiltBlocksProcedure:
			labAPIGetRecentLocallyBuiltBlocksHandler.ServeHTTP(w, r)
		case LabAPIGetSlotDataProcedure:
			labAPIGetSlotDataHandler.ServeHTTP(w, r)
		case LabAPIGetConfigProcedure:
			labAPIGetConfigHandler.ServeHTTP(w, r)
		case LabAPIGetStateExpiryInfoProcedure:
			labAPIGetStateExpiryInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLabAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedLabAPIHandler struct{}

func (UnimplementedLabAPIHandler) GetRecentLocallyBuiltBlocks(context.Context, *connect.Request[proto.GetRecentLocallyBuiltBlocksRequest]) (*connect.Response[proto.GetRecentLocallyBuiltBlocksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("labapi.LabAPI.GetRecentLocallyBuiltBlocks is not implemented"))
}

func (UnimplementedLabAPIHandler) GetSlotData(context.Context, *connect.Request[proto.GetSlotDataRequest]) (*connect.Response[proto.GetSlotDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("labapi.LabAPI.GetSlotData is not implemented"))
}

func (UnimplementedLabAPIHandler) GetConfig(context.Context, *connect.Request[proto.GetConfigRequest]) (*connect.Response[proto.GetConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("labapi.LabAPI.GetConfig is not implemented"))
}

func (UnimplementedLabAPIHandler) GetStateExpiryInfo(context.Context, *connect.Request[proto.GetStateExpiryInfoRequest]) (*connect.Response[proto.GetStateExpiryInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("labapi.LabAPI.GetStateExpiryInfo is not implemented"))
}
