syntax = "proto3";

package labapi;

option go_package = "github.com/ethpandaops/lab/backend/pkg/api/proto";

import "backend/pkg/server/proto/beacon_slots/beacon_slots.proto";
import "backend/pkg/server/proto/lab/lab.proto";
import "backend/pkg/server/proto/state_expiry/state_expiry.proto";

service LabAPI {
  rpc GetRecentLocallyBuiltBlocks(GetRecentLocallyBuiltBlocksRequest) returns (GetRecentLocallyBuiltBlocksResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  rpc GetSlotData(GetSlotDataRequest) returns (GetSlotDataResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  rpc GetConfig(GetConfigRequest) returns (GetConfigResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  rpc GetStateExpiryInfo(GetStateExpiryInfoRequest) returns (GetStateExpiryInfoResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
}

message GetSlotDataRequest {
  string network = 1;
  uint64 slot = 2;
}

message GetSlotDataResponse {
  beacon_slots.BeaconSlotData data = 1;
}

message GetRecentLocallyBuiltBlocksRequest {
  string network = 1;
}

message GetRecentLocallyBuiltBlocksResponse {
  repeated beacon_slots.LocallyBuiltSlotBlocks slot_blocks = 1;
}

message GetConfigRequest {
  // Empty request
}

message GetConfigResponse {
  lab.FrontendConfig config = 1;
}

message GetStateExpiryInfoRequest {
  string network = 1;
}

message GetStateExpiryInfoResponse {
  state_expiry.StateExpiryInfo data = 1;
}
