// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: backend/pkg/api/proto/lab_api.proto

package proto

import (
	beacon_slots "github.com/ethpandaops/lab/backend/pkg/server/proto/beacon_slots"
	lab "github.com/ethpandaops/lab/backend/pkg/server/proto/lab"
	state_expiry "github.com/ethpandaops/lab/backend/pkg/server/proto/state_expiry"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSlotDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Slot    uint64 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *GetSlotDataRequest) Reset() {
	*x = GetSlotDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSlotDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotDataRequest) ProtoMessage() {}

func (x *GetSlotDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotDataRequest.ProtoReflect.Descriptor instead.
func (*GetSlotDataRequest) Descriptor() ([]byte, []int) {
	return file_backend_pkg_api_proto_lab_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetSlotDataRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetSlotDataRequest) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type GetSlotDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *beacon_slots.BeaconSlotData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetSlotDataResponse) Reset() {
	*x = GetSlotDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSlotDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotDataResponse) ProtoMessage() {}

func (x *GetSlotDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotDataResponse.ProtoReflect.Descriptor instead.
func (*GetSlotDataResponse) Descriptor() ([]byte, []int) {
	return file_backend_pkg_api_proto_lab_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetSlotDataResponse) GetData() *beacon_slots.BeaconSlotData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetRecentLocallyBuiltBlocksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *GetRecentLocallyBuiltBlocksRequest) Reset() {
	*x = GetRecentLocallyBuiltBlocksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecentLocallyBuiltBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentLocallyBuiltBlocksRequest) ProtoMessage() {}

func (x *GetRecentLocallyBuiltBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentLocallyBuiltBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetRecentLocallyBuiltBlocksRequest) Descriptor() ([]byte, []int) {
	return file_backend_pkg_api_proto_lab_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecentLocallyBuiltBlocksRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type GetRecentLocallyBuiltBlocksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotBlocks []*beacon_slots.LocallyBuiltSlotBlocks `protobuf:"bytes,1,rep,name=slot_blocks,json=slotBlocks,proto3" json:"slot_blocks,omitempty"`
}

func (x *GetRecentLocallyBuiltBlocksResponse) Reset() {
	*x = GetRecentLocallyBuiltBlocksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecentLocallyBuiltBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentLocallyBuiltBlocksResponse) ProtoMessage() {}

func (x *GetRecentLocallyBuiltBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentLocallyBuiltBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetRecentLocallyBuiltBlocksResponse) Descriptor() ([]byte, []int) {
	return file_backend_pkg_api_proto_lab_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecentLocallyBuiltBlocksResponse) GetSlotBlocks() []*beacon_slots.LocallyBuiltSlotBlocks {
	if x != nil {
		return x.SlotBlocks
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_backend_pkg_api_proto_lab_api_proto_rawDescGZIP(), []int{4}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *lab.FrontendConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_backend_pkg_api_proto_lab_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetConfigResponse) GetConfig() *lab.FrontendConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetStateExpiryInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *GetStateExpiryInfoRequest) Reset() {
	*x = GetStateExpiryInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateExpiryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateExpiryInfoRequest) ProtoMessage() {}

func (x *GetStateExpiryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateExpiryInfoRequest.ProtoReflect.Descriptor instead.
func (*GetStateExpiryInfoRequest) Descriptor() ([]byte, []int) {
	return file_backend_pkg_api_proto_lab_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetStateExpiryInfoRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type GetStateExpiryInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *state_expiry.StateExpiryInfo `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetStateExpiryInfoResponse) Reset() {
	*x = GetStateExpiryInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateExpiryInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateExpiryInfoResponse) ProtoMessage() {}

func (x *GetStateExpiryInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_pkg_api_proto_lab_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateExpiryInfoResponse.ProtoReflect.Descriptor instead.
func (*GetStateExpiryInfoResponse) Descriptor() ([]byte, []int) {
	return file_backend_pkg_api_proto_lab_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetStateExpiryInfoResponse) GetData() *state_expiry.StateExpiryInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_backend_pkg_api_proto_lab_api_proto protoreflect.FileDescriptor

var file_backend_pkg_api_proto_lab_api_proto_rawDesc = []byte{
	0x0a, 0x23, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x62, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x61, 0x62, 0x61, 0x70, 0x69, 0x1a, 0x38, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x73,
	0x6c, 0x6f, 0x74, 0x73, 0x2f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x73, 0x6c, 0x6f, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6c, 0x61, 0x62, 0x2f, 0x6c, 0x61, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x38, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x53, 0x6c, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x47, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x73, 0x6c, 0x6f, 0x74,
	0x73, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x53, 0x6c, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63,
	0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x6c, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63,
	0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a,
	0x0b, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x73, 0x6c, 0x6f, 0x74,
	0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x53, 0x6c,
	0x6f, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x0a, 0x73, 0x6c, 0x6f, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6c, 0x61, 0x62, 0x2e, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x35, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x22, 0x4f, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0xfb, 0x02, 0x0a, 0x06, 0x4c, 0x61, 0x62, 0x41, 0x50, 0x49, 0x12, 0x7b, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x6c,
	0x79, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x2a, 0x2e, 0x6c,
	0x61, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x6c, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6c, 0x61, 0x62, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x6c, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12, 0x4b, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x53, 0x6c, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x2e, 0x6c, 0x61, 0x62, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x61, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12, 0x45, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x2e, 0x6c, 0x61, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x6c, 0x61, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12, 0x60,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x2e, 0x6c, 0x61, 0x62, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6c, 0x61, 0x62, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65,
	0x74, 0x68, 0x70, 0x61, 0x6e, 0x64, 0x61, 0x6f, 0x70, 0x73, 0x2f, 0x6c, 0x61, 0x62, 0x2f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_pkg_api_proto_lab_api_proto_rawDescOnce sync.Once
	file_backend_pkg_api_proto_lab_api_proto_rawDescData = file_backend_pkg_api_proto_lab_api_proto_rawDesc
)

func file_backend_pkg_api_proto_lab_api_proto_rawDescGZIP() []byte {
	file_backend_pkg_api_proto_lab_api_proto_rawDescOnce.Do(func() {
		file_backend_pkg_api_proto_lab_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_pkg_api_proto_lab_api_proto_rawDescData)
	})
	return file_backend_pkg_api_proto_lab_api_proto_rawDescData
}

var file_backend_pkg_api_proto_lab_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_backend_pkg_api_proto_lab_api_proto_goTypes = []any{
	(*GetSlotDataRequest)(nil),                  // 0: labapi.GetSlotDataRequest
	(*GetSlotDataResponse)(nil),                 // 1: labapi.GetSlotDataResponse
	(*GetRecentLocallyBuiltBlocksRequest)(nil),  // 2: labapi.GetRecentLocallyBuiltBlocksRequest
	(*GetRecentLocallyBuiltBlocksResponse)(nil), // 3: labapi.GetRecentLocallyBuiltBlocksResponse
	(*GetConfigRequest)(nil),                    // 4: labapi.GetConfigRequest
	(*GetConfigResponse)(nil),                   // 5: labapi.GetConfigResponse
	(*GetStateExpiryInfoRequest)(nil),           // 6: labapi.GetStateExpiryInfoRequest
	(*GetStateExpiryInfoResponse)(nil),          // 7: labapi.GetStateExpiryInfoResponse
	(*beacon_slots.BeaconSlotData)(nil),         // 8: beacon_slots.BeaconSlotData
	(*beacon_slots.LocallyBuiltSlotBlocks)(nil), // 9: beacon_slots.LocallyBuiltSlotBlocks
	(*lab.FrontendConfig)(nil),                  // 10: lab.FrontendConfig
	(*state_expiry.StateExpiryInfo)(nil),        // 11: state_expiry.StateExpiryInfo
}
var file_backend_pkg_api_proto_lab_api_proto_depIdxs = []int32{
	8,  // 0: labapi.GetSlotDataResponse.data:type_name -> beacon_slots.BeaconSlotData
	9,  // 1: labapi.GetRecentLocallyBuiltBlocksResponse.slot_blocks:type_name -> beacon_slots.LocallyBuiltSlotBlocks
	10, // 2: labapi.GetConfigResponse.config:type_name -> lab.FrontendConfig
	11, // 3: labapi.GetStateExpiryInfoResponse.data:type_name -> state_expiry.StateExpiryInfo
	2,  // 4: labapi.LabAPI.GetRecentLocallyBuiltBlocks:input_type -> labapi.GetRecentLocallyBuiltBlocksRequest
	0,  // 5: labapi.LabAPI.GetSlotData:input_type -> labapi.GetSlotDataRequest
	4,  // 6: labapi.LabAPI.GetConfig:input_type -> labapi.GetConfigRequest
	6,  // 7: labapi.LabAPI.GetStateExpiryInfo:input_type -> labapi.GetStateExpiryInfoRequest
	3,  // 8: labapi.LabAPI.GetRecentLocallyBuiltBlocks:output_type -> labapi.GetRecentLocallyBuiltBlocksResponse
	1,  // 9: labapi.LabAPI.GetSlotData:output_type -> labapi.GetSlotDataResponse
	5,  // 10: labapi.LabAPI.GetConfig:output_type -> labapi.GetConfigResponse
	7,  // 11: labapi.LabAPI.GetStateExpiryInfo:output_type -> labapi.GetStateExpiryInfoResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_backend_pkg_api_proto_lab_api_proto_init() }
func file_backend_pkg_api_proto_lab_api_proto_init() {
	if File_backend_pkg_api_proto_lab_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backend_pkg_api_proto_lab_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetSlotDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_pkg_api_proto_lab_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetSlotDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_pkg_api_proto_lab_api_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetRecentLocallyBuiltBlocksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_pkg_api_proto_lab_api_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetRecentLocallyBuiltBlocksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_pkg_api_proto_lab_api_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_pkg_api_proto_lab_api_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_pkg_api_proto_lab_api_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetStateExpiryInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_pkg_api_proto_lab_api_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetStateExpiryInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_pkg_api_proto_lab_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_pkg_api_proto_lab_api_proto_goTypes,
		DependencyIndexes: file_backend_pkg_api_proto_lab_api_proto_depIdxs,
		MessageInfos:      file_backend_pkg_api_proto_lab_api_proto_msgTypes,
	}.Build()
	File_backend_pkg_api_proto_lab_api_proto = out.File
	file_backend_pkg_api_proto_lab_api_proto_rawDesc = nil
	file_backend_pkg_api_proto_lab_api_proto_goTypes = nil
	file_backend_pkg_api_proto_lab_api_proto_depIdxs = nil
}
